### ISSUE TITLE
Fitting breaks with ArgumentError from output console 

### ISSUE THREAD

**Issue by AntonKolmakov** [funbox/fitting#121]
I have doc.abip with long name method api, as long as I running `bundle e rake fitting:report`
This is the full trace running with debug:
```
ArgumentError: negative argument
/Users/antonkolmakov/.rvm/gems/ruby-3.0.1/gems/fitting-2.17.0/lib/fitting/report/console.rb:18:in `*'
/Users/antonkolmakov/.rvm/gems/ruby-3.0.1/gems/fitting-2.17.0/lib/fitting/report/console.rb:18:in `block (2 levels) in output'
/Users/antonkolmakov/.rvm/gems/ruby-3.0.1/gems/fitting-2.17.0/lib/fitting/report/console.rb:16:in `each'
/Users/antonkolmakov/.rvm/gems/ruby-3.0.1/gems/fitting-2.17.0/lib/fitting/report/console.rb:16:in `inject'
/Users/antonkolmakov/.rvm/gems/ruby-3.0.1/gems/fitting-2.17.0/lib/fitting/report/console.rb:16:in `block in output'
/Users/antonkolmakov/.rvm/gems/ruby-3.0.1/gems/fitting-2.17.0/lib/fitting/report/console.rb:13:in `each'
/Users/antonkolmakov/.rvm/gems/ruby-3.0.1/gems/fitting-2.17.0/lib/fitting/report/console.rb:13:in `inject'
/Users/antonkolmakov/.rvm/gems/ruby-3.0.1/gems/fitting-2.17.0/lib/fitting/report/console.rb:13:in `output'
/Users/antonkolmakov/.rvm/gems/ruby-3.0.1/gems/fitting-2.17.0/lib/tasks/fitting.rake:84:in `block (2 levels) in <top (required)>'
/Users/antonkolmakov/.rvm/gems/ruby-3.0.1/gems/unilog-2.5.2/lib/unilog/rake_logging.rb:7:in `block in invoke'
/Users/antonkolmakov/.rvm/gems/ruby-3.0.1/gems/unilog-2.5.2/lib/unilog.rb:92:in `within_context'
/Users/antonkolmakov/.rvm/gems/ruby-3.0.1/gems/unilog-2.5.2/lib/unilog/rake_logging.rb:4:in `invoke'
/Users/antonkolmakov/.rvm/gems/ruby-3.0.1/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/Users/antonkolmakov/.rvm/gems/ruby-3.0.1/bin/ruby_executable_hooks:22:in `eval'
/Users/antonkolmakov/.rvm/gems/ruby-3.0.1/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => fitting:report
```

**Comment by StoneGod** [comment]
kek

**Comment by tuwilof** [comment]
may be use ready gem for output table in console
how in gem https://github.com/odlp/rspec_overview
