### ISSUE TITLE
Undefined method 'not_coverage'

### ISSUE THREAD

**Issue by vassilevsky** [funbox/fitting#4]
```
NoMethodError: undefined method `not_coverage' for #<Fitting::Route:0x007fabc5917c10>
  /Users/vassilevsky/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fitting-1.6.0/lib/fitting/statistics.rb:12:in `not_coverage?'
  /Users/vassilevsky/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fitting-1.6.0/lib/fitting.rb:48:in `run_specs'
  /Users/vassilevsky/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:93:in `run'
  /Users/vassilevsky/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
  /Users/vassilevsky/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
  /Users/vassilevsky/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
  /Users/vassilevsky/.rbenv/versions/2.3.3-p0/bin/rspec:22:in `load'
  /Users/vassilevsky/.rbenv/versions/2.3.3-p0/bin/rspec:22:in `<top (required)>'
```

**Comment by tuwilof** [comment]
Unacceptable!
Fix ready
